# Configuration for experiments

method: da           # method to search
func: ackley         # test function
dims: 10             # problem dimension
num_samples: 20      # number of samples to collect in the search
init_samples: 200    # number of initialisation data points for training initial surrogate model 


# Hyper-parameters for different DFO methods
dfo_method_args:
  turbo:
    n_trust_regions: 5        # Number trust regions: TuRBO-1 will be used if set to 1, otherwise TuRBOM will be used
    n_repeat: 1               # Number repeat time for the same condition
    batch_size: 1             # How large batch size TuRBO uses
    verbose: True             # Print information from each batch
    use_ard: True             # Set to true if you want to use ARD for the GP kernel 
    max_cholesky_size: 2000   # When we switch from Cholesky to Lanczos
    n_training_steps: 50      # Number of steps of ADAM to learn the hypers
    min_cuda: 1024            # Run on the CPU for small datasets
    device: cpu               # "cpu" or "cuda"
    dtype: float32            # float64 or float32

  lamcts:
    Cp: 1                     # Cp for MCTS
    leaf_size: 10             # Tree leaf size
    kernel_type: linear       # SVM configruation
    gamma_type: auto          # SVM configruation

  da:
    initial_temp: 0.05

  doo:
    explr_p: 0.01

  voo:
    explr_p: 0.001
    sampling_mode: centered_uniform
    switch_counter: 100